sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - chmod +x mvnw

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "dev" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=kekedigabor92/emailservice
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: kekedigabor92-emailservice
  on:
    branch: "dev"